#!/bin/bash
echo "🚀 ClinicalForge Quick Start"
echo "=========================="
echo ""
echo "1. Deploy Firebase Rules:"
echo "   - Go to: https://console.firebase.google.com/"
echo "   - Select project: hdms-a8e42"
echo "   - Navigate to: Firestore Database → Rules"
echo "   - Copy rules from firestore.rules"
echo "   - Paste and click 'Publish'"
echo ""
echo "2. Add Test Data (Optional):"
echo "   - In Firebase Console → Firestore Database"
echo "   - Create collection: clinicalLogic"
echo "   - Add 3 test documents (see complete-setup-guide.md)"
echo ""
echo "3. Start Application:"
echo "   npm run dev"
echo ""
echo "4. Access Application:"
echo "   - URL: http://localhost:3000"
echo "   - Admin: http://localhost:3000/login"
echo "   - Password: Data Debo Na"
echo ""
echo "🎉 ClinicalForge is ready!"
